### ISSUE TITLE
Official english version

### ISSUE THREAD

**Issue by berets76** [telerik/blazor-ui-messages#2]
Hi,
where can we found the latest version of the official english default TelerikMessages.resx ?

Thanks

**Comment by marin-bratanov** [comment]
In the official demos. They are available in the `demos` folder of your local installation. In the `Resources` folder, there is the `Messages.resx` file we keep up to date with each release.

You can read more about this in the documentation https://docs.telerik.com/blazor-ui/globalization/localization
